version: "3"
services:
  django:
    environment:
      - "STATIC_ROOT=/var/lib/static"
    volumes:
      - "./server:/usr/src/app"
      - "django_static:/var/lib/static"
      - "./server/upload_files:/usr/src/app/upload_files"
    restart: always
  postgres:
    command: postgres -c max_connections=10000
    restart: always
  redis:
    restart: always
  nginx:
    volumes:
      - "./nginx/nginx.prod.conf:/etc/nginx/nginx.conf"
      - "client_dist:/usr/src/app/client"
      - "django_static:/usr/src/app/django_static"
      - "./server/upload_files:/usr/src/app/upload_files"
    ports:
      - "8002:80"
    restart: always
  nodejs:
    volumes:
      - "./client/src:/usr/src/app/src"
      - "client_dist:/usr/src/app/dist"

volumes:
  database:
    driver: local
  django_static:
    driver: local
  client_dist:
    driver: local