version: "3"
services:
  django:
    build: server
    links:
      - "postgres"
    env_file:
      - ".env"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./server:/usr/src/app"
      - "./server/upload_files:/usr/src/app/upload_files"
  postgres:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ".env"
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./server/upload_files:/usr/src/app/upload_files"
    links:
      - "django"
      - "nodejs"
    ports:
      - "8008:80"
  nodejs:
    build: client
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ".env"
    volumes:
      - "./client/src:/usr/src/app/src"

volumes:
  database:
    driver: local