# Generated by Django 3.0.5 on 2020-04-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='is_annonymous',
            field=models.BooleanField(default=False, verbose_name='匿名投稿'),
        ),
    ]
