# Generated by Django 3.0.5 on 2020-04-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_chatlog_is_annonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='is_annonymous',
            new_name='is_anonymous',
        ),
    ]
