# Generated by Django 3.0.5 on 2020-05-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='start_time',
        ),
        migrations.AddField(
            model_name='circle',
            name='start_time_sec',
            field=models.IntegerField(blank=True, null=True, verbose_name='開始時間(秒)'),
        ),
    ]
