# Generated by Django 3.1.7 on 2021-03-24 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_movie_uploaded',
            field=models.BooleanField(default=False, verbose_name='動画アップロード済みか'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='pamphlet',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='サークル資料(PDF)'),
        ),
    ]
