# Generated by Django 3.1.7 on 2021-03-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_auto_20210325_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Slack ID'),
        ),
    ]
