# Generated by Django 3.1.7 on 2021-03-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_user_slack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Slack ID'),
        ),
    ]
