# Generated by Django 3.1.7 on 2021-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_auto_20210412_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='thumbnail_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='circle',
            name='logo_uploaded_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='ロゴアップロード時刻'),
        ),
        migrations.AddField(
            model_name='circle',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='ロゴURL'),
        ),
    ]
