# Generated by Django 3.0.5 on 2020-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_auto_20200505_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '開始前'), (1, '開催中'), (2, '終了')], default=0, verbose_name='開催状況')),
                ('started_time', models.DateTimeField(blank=True, null=True, verbose_name='実際のイベント開始日時')),
                ('planning_start_time', models.DateTimeField(blank=True, null=True, verbose_name='イベント開始予定日時')),
            ],
        ),
    ]
