# Generated by Django 3.1.7 on 2021-04-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_auto_20210412_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlogreaction',
            name='id',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='receive_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='受信者'),
        ),
        migrations.AddField(
            model_name='chatlogreaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='receiver_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_chat_logs', to='meets.circle', verbose_name='宛先サークル'),
        ),
    ]
