# Generated by Django 3.1.7 on 2021-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0009_remove_chatlog_receive_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlogreaction',
            name='reaction',
            field=models.CharField(max_length=4, verbose_name='リアクション'),
        ),
    ]
