# Generated by Django 3.1.7 on 2021-04-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0010_auto_20210416_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('type', models.CharField(choices=[('circle_start', 'サークル開始'), ('question_start', 'クイズ・アンケート開始'), ('question_result', 'クイズ解答・アンケート結果発表'), ('quiz_final_result', 'クイズ最終結果発表'), ('tutorial_info_start', '情報画面チュートリアル開始'), ('tutorial_chat_start', 'チャット画面チュートリアル開始'), ('tutorial_list_start', 'サークルリストチュートリアル開始'), ('tutorial_hashtag_start', 'ハッシュタグチュートリアル開始'), ('pr_url_start', 'URL宣伝'), ('final_start', '最終画面表示')], max_length=30, verbose_name='種類')),
                ('start_time_sec', models.IntegerField(blank=True, null=True, verbose_name='開始時刻(秒)')),
                ('pr_url', models.URLField(blank=True, null=True, verbose_name='広告URL')),
                ('pr_text', models.TextField(blank=True, null=True, verbose_name='広告テキスト')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='circle',
            name='start_time_sec',
        ),
        migrations.RemoveField(
            model_name='question',
            name='start_time_sec',
        ),
        migrations.RemoveField(
            model_name='question',
            name='thinking_time_sec',
        ),
        migrations.AddField(
            model_name='questionselection',
            name='text',
            field=models.TextField(default='', verbose_name='選択肢'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(default='', verbose_name='問題/質問'),
        ),
        migrations.AlterField(
            model_name='questionselection',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='正解か'),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='meets.questionselection', verbose_name='選択'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to=settings.AUTH_USER_MODEL, verbose_name='クイズ・アンケート回答'),
        ),
        migrations.AddField(
            model_name='event',
            name='circle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='meets.circle', verbose_name='サークル'),
        ),
        migrations.AddField(
            model_name='event',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='meets.question', verbose_name='クイズ/アンケート'),
        ),
    ]
