# Generated by Django 3.1.7 on 2021-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0011_auto_20210418_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='is_admin_message',
            field=models.BooleanField(default=False, verbose_name='運営メッセージ'),
        ),
    ]
