# Generated by Django 3.1.7 on 2021-04-18 16:58

from django.db import migrations, models
import meets.models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0012_chatlog_is_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=meets.models.get_circle_thumbnail_path, verbose_name='サムネイル画像'),
        ),
    ]
