# Generated by Django 3.1.7 on 2021-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0016_auto_20210421_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='archive_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='アーカイブURL'),
        ),
        migrations.AlterField(
            model_name='status',
            name='streaming_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ストリーミングURL'),
        ),
    ]
