# Generated by Django 3.1.7 on 2021-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0017_auto_20210421_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['event__start_time_sec', 'event__order']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time_sec', 'order']},
        ),
        migrations.RemoveField(
            model_name='circle',
            name='order',
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='順番'),
        ),
    ]
