# Generated by Django 3.1.7 on 2021-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0018_auto_20210421_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='can_circle_join',
            field=models.BooleanField(default=False, verbose_name='新規サークル受付中'),
        ),
        migrations.AddField(
            model_name='status',
            name='can_circle_logo_upload',
            field=models.BooleanField(default=False, verbose_name='ロゴアップロード受付中'),
        ),
        migrations.AddField(
            model_name='status',
            name='can_circle_movie_upload',
            field=models.BooleanField(default=False, verbose_name='動画アップロード受付中'),
        ),
        migrations.AddField(
            model_name='status',
            name='can_circle_pamphlet_upload',
            field=models.BooleanField(default=False, verbose_name='資料アップロード受付中'),
        ),
    ]
