# Generated by Django 3.1.7 on 2021-04-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0019_auto_20210426_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '開場前'), (1, '開場可'), (2, '配信終了')], default=0, verbose_name='開催状況'),
        ),
    ]
