# Generated by Django 3.1.7 on 2021-04-29 06:44

import django.core.validators
from django.db import migrations, models
import meets.models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0020_auto_20210426_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='final_questionnaire_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='終了後アンケートURL'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='pamphlet',
            field=models.FileField(blank=True, null=True, upload_to=meets.models.get_circle_pamphlet_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='サークル資料(PDF)'),
        ),
    ]
